%% Clear previous workspace
clear
clc

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /media/anthony/Storage/wfds_storage/trails_pl3d_devices/output/trails_pl3d_with_devices_devc.csv
%
% Auto-generated by MATLAB on 15-May-2020 14:01:07

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["s", "kWm2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
d = readtable("/media/anthony/Storage/wfds_storage/trails_pl3d_devices/output/trails_pl3d_with_devices_devc.csv", opts);

%% Convert to output type
d = table2array(d);

%% Clear temporary variables
clear opts

x = 72;
y = 134;
z = 37;

%% Integrate Rad Heat Flux Gas at each time step with a for Loop
size_d = size(d);
Integrated_RadHeatFluxGas = zeros(size_d(1), 1);
for index = 2 : size_d(1)
    RadHeatFluxGas = d(1:index, 2);
    Integrated_RadHeatFluxGas(index,1) = trapz(d(1:index,1),RadHeatFluxGas);
end
% Calculate TDU by exponentiating element-wise to the 4/3
TDU_rad = power(Integrated_RadHeatFluxGas,(4/3));
TDU_rad(imag(TDU_rad) ~= 0) = 0;
output = zeros(size_d(1),5);
%output(1:end,1) = d(1:end,1);
output(1:end,1) = -1:2099;
output(1:end,2) = TDU_rad;
output(1:end,3) = x;
output(1:end,4) = y;
output(1:end,5) = z;

% csvwrite("/media/anthony/Storage/wfds_storage/trails_pl3d_devices/output/TDU_rad.csv", output(2:end,1:end));
T = array2table(output(2:end,1:end), 'VariableNames', {'time', 'TDU', 'x', 'y', 'z'});
writetable(T, "/media/anthony/Storage/wfds_storage/trails_pl3d_devices/output/TDU_rad.csv")




